# Generated by Django 5.2.5 on 2025-08-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("population", models.IntegerField()),
                ("climates", models.JSONField(default=list)),
                ("terrains", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "planets",
            },
        ),
    ]
